### ISSUE TITLE
[Tracking] 2.1.0

### ISSUE THREAD

**Issue by maxrimue** [tj/n#308]
As proposed changes are spread into several issues, I wanted to cover up the planned and proposed changes for 2.1.0 in order to get feedback and an approach on how to establish the changes:
#### 1. Issues from the Milestone:
- [ ] Support any semver value for install or use (#192) 
- [ ] "n use" style command for invoking npm (#185)
- [ ] Add support for "x", "d", or delete to remove a selected version (#139)  
#### 2. Proposed Changes:
- [ ] Removing OR repairing support for the `stable` keyboard (due to convergence, #307)
- [ ] Make n be able to distinguish between different architectures in local storage (#306) 

I would like to receive some feedback for this list, as well as ideas for the timing.

**Comment by maxrimue** [comment]
@tedgaydos What's your opinion on it?

**Comment by qw3rtman** [comment]
I think we should release `2.1.0` as soon as possible and move these changes to the next release. It's been 4 months since our last release and features (such as `n lts`) are not available to the majority of people.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
